async function initLogin(){const form=document.getElementById("loginForm");const {data:{session}}=await supabaseClient.auth.getSession();if(session)location.href="dashboard.html";form.onsubmit=async e=>{e.preventDefault();const f=new FormData(form);const {error}=await supabaseClient.auth.signInWithPassword({email:f.get("email"),password:f.get("password")});document.getElementById("loginMsg").textContent=error?error.message:"Connexion…";if(!error)location.href="dashboard.html"}}
async function protectAdmin(){const {data:{session}}=await supabaseClient.auth.getSession();if(!session){location.href="index.html";return}document.getElementById("logout")?.addEventListener("click",async()=>{await supabaseClient.auth.signOut();location.href="index.html"})}
async function loadDashboard(){const [p,o]=await Promise.all([supabaseClient.from("products").select("id",{count:"exact",head:true}),supabaseClient.from("orders").select("id,status,total")]);const orders=o.data||[];const revenue=orders.filter(x=>x.status==="delivered").reduce((s,x)=>s+Number(x.total),0);document.getElementById("stats").innerHTML=`<div class="stat"><b>${p.count||0}</b><span>Produits</span></div><div class="stat"><b>${orders.length}</b><span>Commandes</span></div><div class="stat"><b>${orders.filter(x=>x.status==="new").length}</b><span>Nouvelles</span></div><div class="stat"><b>${orders.filter(x=>x.status==="delivered").length}</b><span>Livrées</span></div><div class="stat"><b>${new Intl.NumberFormat("fr-DZ").format(revenue)} DA</b><span>CA livré</span></div>`}
async function loadProducts(){const {data,error}=await supabaseClient.from("products").select("*").order("created_at",{ascending:false});const el=document.getElementById("adminProducts");if(error){el.textContent=error.message;return}el.innerHTML=(data||[]).map(p=>`<div class="admin-row"><img src="${p.image_url||"https://placehold.co/100"}"><div><b>${escapeHtml(p.name)}</b><div>${money(p.price)} · ${escapeHtml(p.category||"Sans catégorie")} · ${p.active?"Visible":"Masqué"}</div></div><div><button onclick='editProduct(${JSON.stringify(p)})'>Modifier</button> <button onclick="deleteProduct('${p.id}')">Supprimer</button></div></div>`).join("")}
function openProductForm(){document.getElementById("productFormWrap").classList.remove("hidden");document.getElementById("productForm").reset();document.querySelector('[name="active"]').checked=true}
function closeProductForm(){document.getElementById("productFormWrap").classList.add("hidden")}
function editProduct(p){openProductForm();const f=document.getElementById("productForm");f.id.value=p.id;f.name.value=p.name;f.price.value=p.price;f.category.value=p.category||"";f.description.value=p.description||"";f.active.checked=p.active}
async function deleteProduct(id){if(!confirm("Supprimer ce produit ?"))return;const {error}=await supabaseClient.from("products").delete().eq("id",id);if(error)alert(error.message);else loadProducts()}
document.addEventListener("submit",async e=>{if(e.target.id!=="productForm")return;e.preventDefault();const f=e.target,fd=new FormData(f),id=fd.get("id");let image_url=null;const file=f.image.files[0];if(file){const path=`${crypto.randomUUID()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,"_")}`;const up=await supabaseClient.storage.from("product-images").upload(path,file,{upsert:false});if(up.error){document.getElementById("productMsg").textContent=up.error.message;return}image_url=supabaseClient.storage.from("product-images").getPublicUrl(path).data.publicUrl}const data={name:fd.get("name"),price:Number(fd.get("price")),category:fd.get("category"),description:fd.get("description"),active:f.active.checked};if(image_url)data.image_url=image_url;let r=id?await supabaseClient.from("products").update(data).eq("id",id):await supabaseClient.from("products").insert(data);if(r.error)document.getElementById("productMsg").textContent=r.error.message;else{closeProductForm();loadProducts()}})
async function loadOrders(){const status=document.getElementById("statusFilter")?.value;let q=supabaseClient.from("orders").select("*").order("created_at",{ascending:false});if(status)q=q.eq("status",status);const {data,error}=await q;const el=document.getElementById("orders");if(error){el.textContent=error.message;return}el.innerHTML=(data||[]).map(o=>`<article class="order card"><div class="pagehead"><div><h3>#${o.id.slice(0,8)}</h3><p>${new Date(o.created_at).toLocaleString("fr-DZ")}</p></div><select onchange="updateOrder('${o.id}',this.value)">${["new","confirmed","shipping","delivered","cancelled"].map(s=>`<option value="${s}" ${o.status===s?"selected":""}>${statusLabel(s)}</option>`).join("")}</select></div><p><b>${escapeHtml(o.customer_name)}</b> · ${escapeHtml(o.phone)}</p><p>${escapeHtml(o.wilaya)} — ${escapeHtml(o.commune)}<br>${escapeHtml(o.address)}</p><details><summary>Produits</summary><pre>${escapeHtml(JSON.stringify(o.items,null,2))}</pre></details><strong>Total : ${money(o.total)}</strong> <button onclick="deleteOrder('${o.id}')">🗑️ Supprimer</button></article>`).join("")}
const statusLabel=s=>({new:"Nouvelle",confirmed:"Confirmée",shipping:"En livraison",delivered:"Livrée",cancelled:"Annulée"}[s]||s);
async function updateOrder(id,status){const {error}=await supabaseClient.from("orders").update({status}).eq("id",id);if(error)alert(error.message)}
async function deleteOrder(id){if(!confirm("Supprimer définitivement cette commande ?"))return;const {error}=await supabaseClient.from("orders").delete().eq("id",id);if(error)alert(error.message);else loadOrders()}
