const money = n => new Intl.NumberFormat("fr-DZ").format(Number(n)) + " DA";
const wilayas = ["Adrar","Chlef","Laghouat","Oum El Bouaghi","Batna","Béjaïa","Biskra","Béchar","Blida","Bouira","Tamanrasset","Tébessa","Tlemcen","Tiaret","Tizi Ouzou","Alger","Djelfa","Jijel","Sétif","Saïda","Skikda","Sidi Bel Abbès","Annaba","Guelma","Constantine","Médéa","Mostaganem","M'Sila","Mascara","Ouargla","Oran","El Bayadh","Illizi","Bordj Bou Arréridj","Boumerdès","El Tarf","Tindouf","Tissemsilt","El Oued","Khenchela","Souk Ahras","Tipaza","Mila","Aïn Defla","Naâma","Aïn Témouchent","Ghardaïa","Relizane","Timimoun","Bordj Badji Mokhtar","Ouled Djellal","Béni Abbès","In Salah","In Guezzam","Touggourt","Djanet","El M'Ghair","El Meniaa"];
const shipping = Object.fromEntries(wilayas.map(w => [w, 500]));
const cartKey = "shop_cart_v1";
const getCart = () => JSON.parse(localStorage.getItem(cartKey) || "[]");
const saveCart = c => {localStorage.setItem(cartKey, JSON.stringify(c)); updateCartCount();};
function updateCartCount(){const n=getCart().reduce((s,x)=>s+x.qty,0); document.querySelectorAll("#cartCount").forEach(e=>e.textContent=n)}
async function getProducts(){const {data,error}=await supabaseClient.from("products").select("*").eq("active",true).order("created_at",{ascending:false}); if(error) throw error; return data||[]}
function productCard(p){return `<article class="product-card"><a href="product.html?id=${p.id}"><img src="${p.image_url||"https://placehold.co/600x600?text=Produit"}" alt=""><div class="pad"><h3>${escapeHtml(p.name)}</h3><p class="price">${money(p.price)}</p></div></a><button class="btn full" onclick='addToCart(${JSON.stringify({id:p.id,name:p.name,price:p.price,image_url:p.image_url})})'>Ajouter au panier</button></article>`}
function escapeHtml(s){return String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
async function loadShop(){updateCartCount();const list=document.getElementById("products");if(!list)return;try{const ps=await getProducts();const render=()=>{const q=(document.getElementById("search").value||"").toLowerCase();const c=document.getElementById("category").value;const x=ps.filter(p=>(p.name.toLowerCase().includes(q)||String(p.description||"").toLowerCase().includes(q))&&(!c||p.category===c));list.innerHTML=x.map(productCard).join("");document.getElementById("empty").classList.toggle("hidden",x.length>0)};[...new Set(ps.map(p=>p.category).filter(Boolean))].forEach(c=>document.getElementById("category").insertAdjacentHTML("beforeend",`<option>${escapeHtml(c)}</option>`));document.getElementById("search").oninput=render;document.getElementById("category").onchange=render;render()}catch(e){list.innerHTML="<p>Configure Supabase dans js/config.js puis recharge la page.</p>"}}
function addToCart(p){const c=getCart(),x=c.find(i=>i.id===p.id);if(x)x.qty++;else c.push({...p,qty:1});saveCart(c);alert("Produit ajouté au panier.");}
function removeItem(id){saveCart(getCart().filter(x=>x.id!==id));renderCart()}
function changeQty(id,d){const c=getCart(),x=c.find(i=>i.id===id);if(!x)return;x.qty+=d;if(x.qty<=0)return removeItem(id);saveCart(c);renderCart()}
function renderCart(){updateCartCount();const el=document.getElementById("cart");if(!el)return;const c=getCart();if(!c.length){el.innerHTML='<div class="card empty">Votre panier est vide.<br><a class="btn" href="index.html">Voir les produits</a></div>';return}const total=c.reduce((s,x)=>s+x.price*x.qty,0);el.innerHTML=`<div class="cart-list">${c.map(x=>`<div class="cart-row"><img src="${x.image_url||"https://placehold.co/100"}"><div><b>${escapeHtml(x.name)}</b><p>${money(x.price)}</p></div><div class="qty"><button onclick="changeQty('${x.id}',-1)">−</button>${x.qty}<button onclick="changeQty('${x.id}',1)">+</button></div><button onclick="removeItem('${x.id}')">🗑️</button></div>`).join("")}</div><div class="card total"><h2>Total produits : ${money(total)}</h2><a class="btn" href="checkout.html">Passer la commande</a></div>`}
async function loadProduct(){updateCartCount();const id=new URLSearchParams(location.search).get("id"),el=document.getElementById("product");if(!id||!el)return;const {data:p,error}=await supabaseClient.from("products").select("*").eq("id",id).single();if(error){el.innerHTML="Produit introuvable.";return}el.innerHTML=`<img src="${p.image_url||"https://placehold.co/700"}><div><p class="eyebrow">${escapeHtml(p.category||"Produit")}</p><h1>${escapeHtml(p.name)}</h1><div class="price big">${money(p.price)}</div><p>${escapeHtml(p.description||"")}</p><button class="btn" onclick='addToCart(${JSON.stringify({id:p.id,name:p.name,price:p.price,image_url:p.image_url})})'>Ajouter au panier</button></div>`}
function initCheckout(){updateCartCount();const form=document.getElementById("checkoutForm");const w=document.getElementById("wilaya");wilayas.forEach(x=>w.insertAdjacentHTML("beforeend",`<option>${x}</option>`));const refresh=()=>{const c=getCart();const p=c.reduce((s,x)=>s+x.price*x.qty,0),f=shipping[w.value]||500;document.getElementById("summary").innerHTML=`Produits : <b>${money(p)}</b><br>Livraison : <b>${money(f)}</b><br><strong>Total : ${money(p+f)}</strong>`};w.onchange=refresh;refresh();form.onsubmit=async e=>{e.preventDefault();const c=getCart();if(!c.length)return;const fd=new FormData(form),products_total=c.reduce((s,x)=>s+x.price*x.qty,0),shipping_fee=shipping[fd.get("wilaya")]||500;const payload={customer_name:fd.get("customer_name"),phone:fd.get("phone"),wilaya:fd.get("wilaya"),commune:fd.get("commune"),address:fd.get("address"),note:fd.get("note"),items:c.map(x=>({id:x.id,name:x.name,price:x.price,qty:x.qty})),products_total,shipping_fee,total:products_total+shipping_fee,status:"new"};const {error}=await supabaseClient.from("orders").insert(payload);const msg=document.getElementById("checkoutMsg");if(error){msg.textContent="Erreur : "+error.message;return}localStorage.removeItem(cartKey);form.reset();msg.textContent="Commande enregistrée avec succès !";msg.className="success";}}}
if(document.getElementById("products"))loadShop();if(document.getElementById("product"))loadProduct();updateCartCount();
